services:
  python-server:
    build:
      context: ./python-server
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./python-server/src:/app/src
    command: ["uvicorn", "src.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]

  node-server:
    build:
      context: ./simple-express-server
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    volumes:
      - ./simple-express-server/src:/usr/src/app/src
      - ./simple-express-server/package.json:/usr/src/app/package.json
      - ./simple-express-server/node_modules:/usr/src/app/node_modules
    command: ["yarn", "start"]
